### ISSUE TITLE
Windows 10 unable to run

### ISSUE THREAD

**Issue by Ygarr** [mikkun/termmaze3d#1]
installed gawk and coreutils
Just after run got cmd window and then it closing straightaway

**Comment by mikkun** [comment]
Hi @Ygarr!

Thanks for reporting. Unfortunately, I don't have Windows 10 to test this.

So, please check the following:
- Does [`awktc.awk`](https://github.com/mikkun/AWKTC) work correctly?
- Are you trying to run the program on WSL?

**Comment by mikkun** [comment]
Hi @Ygarr!

Thanks for reporting. Unfortunately, I don't have Windows 10 to test this.

So, please check the following:
- Does [`awktc.awk`](https://github.com/mikkun/AWKTC) work correctly?
- Are you trying to run the program on WSL?

**Comment by Ygarr** [comment]
Thank for reply.

- No. No Linux subsystem.

Just add awk.exe to path.

- Such things:

```
C:\Users\theuser\AWKTC(master -> origin)
λ awktc.awk
awk: cmd. line:1: C:\Users\theuser\AWKTC\awktc.awk
awk: cmd. line:1:  ^ syntax error
awk: cmd. line:1: C:\Users\theuser\AWKTC\awktc.awk
awk: cmd. line:1:   ^ backslash not last character on line
```

**Comment by mikkun** [comment]
Hi @Ygarr!

> No. No Linux subsystem.

`termmaze3d.awk` and `awktc.awk` only work on Unix-like OS systems, so you need to enable WSL and install a Linux distribution like Ubuntu.

I hope it helps.

**Comment by Ygarr** [comment]
Ok got it. Thanks for your attention
